name: Publish to NPM

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm run lint

      - name: Prettier check
        run: pnpm run format:check

      - name: Dependency graph check
        run: pnpm dep-graph

      - name: Run pre-build script
        run: pnpm run pre-build

      - name: Build
        run: pnpm run build

      - name: TSC build check
        run: pnpm run build:tsc

      - name: Run e2e test
        run: pnpm run test:e2e

      - name: Run unit test with coverage
        run: pnpm run test:unit:c

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/cobertura-coverage.xml

      - name: Run pre-publish script
        run: pnpm run pre-publish

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
